name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: DockerHub

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
      run: echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tomwu618/ip-sonar:$(date +%s)

    - name: Login to Docker Hub
      run: echo "${{ env.ACCESS_TOKEN }}" | docker login -u tomwu618 --password-stdin

    - name: Push Docker image
      run: docker push tomwu618/ip-sonar
