name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Configure DockerHub  # 与 GitHub 中设置的环境名相同

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tomwu618/ip-sonar:$(date +%s)

    - name: Login to Docker Hub
      run: echo "${{ env.ACCESS_TOKEN }}" | docker login -u tomwu618 --password-stdin  # 注意这里使用了 env 而不是 secrets

    - name: Push Docker image
      run: docker push tomwu618/ip-sonar
